from pathlib import Path

from pcb2gcode_ui.options import (
    FILE_OPTIONS,
    OPTION_SPECS,
    SPEC_BY_KEY,
    bool_value,
    default_values,
)


def parse_millproject(path: Path) -> dict[str, str]:
    values = default_values()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        normalized_key = key.strip()
        if normalized_key in SPEC_BY_KEY:
            values[normalized_key] = value.strip()
    return values


def validate_millproject_format(path: Path) -> list[str]:
    messages: list[str] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        if "=" not in line:
            messages.append(f"Line #{line_number}: expected key=value.")
            continue
        key, _value = line.split("=", 1)
        if not key.strip():
            messages.append(f"Line #{line_number}: option name is required.")
    return messages


def write_millproject(path: Path, values: dict[str, str]):
    path.write_text(format_millproject(values, path.parent), encoding="utf-8")


def format_millproject(values: dict[str, str], base_dir: Path = None) -> str:
    lines = [
        "# Generated by pcb2gcode-ui.",
        "# Edit in the GUI and save again to keep this canonical format.",
        "",
    ]
    current_group = ""
    for spec in OPTION_SPECS:
        value = values.get(spec.key, "").strip()
        if not value:
            continue
        if spec.kind == "bool":
            value = "true" if bool_value(value) else "false"
        elif base_dir and (spec.key in FILE_OPTIONS or spec.key == "output-dir"):
            value = _format_path(value, base_dir)
        if spec.group != current_group:
            if current_group:
                lines.append("")
            lines.append(f"# {spec.group}")
            current_group = spec.group
        lines.append(f"{spec.key}={value}")
    lines.append("")
    return "\n".join(lines)


def _format_path(value: str, base_dir: Path) -> str:
    path = Path(value).expanduser()
    if not path.is_absolute():
        return value
    try:
        relative_path = path.relative_to(base_dir)
    except ValueError:
        return value
    if str(relative_path) in {"", "."}:
        return "."
    return str(relative_path)
