from pathlib import Path

from pcb2gcode_ui.options import OPTION_SPECS, SPEC_BY_KEY, bool_value, default_values


def parse_millproject(path: Path) -> dict[str, str]:
    values = default_values()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        normalized_key = key.strip()
        if normalized_key in SPEC_BY_KEY:
            values[normalized_key] = value.strip()
    return values


def write_millproject(path: Path, values: dict[str, str]):
    path.write_text(format_millproject(values), encoding="utf-8")


def format_millproject(values: dict[str, str]) -> str:
    lines = [
        "# Generated by pcb2gcode-ui.",
        "# Edit in the GUI and save again to keep this canonical format.",
        "",
    ]
    current_group = ""
    for spec in OPTION_SPECS:
        value = values.get(spec.key, "").strip()
        if not value:
            continue
        if spec.kind == "bool":
            value = "true" if bool_value(value) else "false"
        if spec.group != current_group:
            if current_group:
                lines.append("")
            lines.append(f"# {spec.group}")
            current_group = spec.group
        lines.append(f"{spec.key}={value}")
    lines.append("")
    return "\n".join(lines)
