from pathlib import Path

from pcb2gcode_ui.millproject import (
    format_millproject,
    parse_millproject,
    validate_millproject_format,
)


def test_parse_millproject_reads_known_options_and_ignores_comments(tmp_path: Path):
    millproject_path = tmp_path / "millproject"
    millproject_path.write_text(
        """
# comment
metric=true
front=board-F.Cu.gbr # inline comment
unknown=value
""",
        encoding="utf-8",
    )

    values = parse_millproject(millproject_path)

    assert values["metric"] == "true"
    assert values["front"] == "board-F.Cu.gbr"
    assert "unknown" not in values


def test_validate_millproject_format_rejects_plain_text_file(tmp_path: Path):
    millproject_path = tmp_path / "notes.txt"
    millproject_path.write_text(
        """
This is not a millproject file.
metric true
""",
        encoding="utf-8",
    )

    assert validate_millproject_format(millproject_path) == [
        "Line #2: expected key=value.",
        "Line #3: expected key=value.",
    ]


def test_validate_millproject_format_allows_comments_blanks_and_unknown_options(tmp_path: Path):
    millproject_path = tmp_path / "millproject"
    millproject_path.write_text(
        """
# comment
unknown=value
zsafe=5 # inline comment
""",
        encoding="utf-8",
    )

    assert validate_millproject_format(millproject_path) == []


def test_format_millproject_writes_canonical_groups():
    content = format_millproject({"metric": "true", "zsafe": "5", "front": "front.gbr"})

    assert "# Generated by pcb2gcode-ui." in content
    assert "# Generic" in content
    assert "metric=true" in content
    assert "# Files" in content
    assert "front=front.gbr" in content
    assert "# CNC" in content
    assert "zsafe=5" in content


def test_format_millproject_stores_paths_relative_to_project_dir(tmp_path: Path):
    content = format_millproject(
        {
            "front": str(tmp_path / "board-F.Cu.gbr"),
            "output-dir": str(tmp_path / "nc"),
        },
        tmp_path,
    )

    assert "front=board-F.Cu.gbr" in content
    assert "output-dir=nc" in content
