from pathlib import Path

from pcb2gcode_ui.millproject import format_millproject, parse_millproject


def test_parse_millproject_reads_known_options_and_ignores_comments(tmp_path: Path):
    millproject_path = tmp_path / "millproject"
    millproject_path.write_text(
        """
# comment
metric=true
front=board-F.Cu.gbr # inline comment
unknown=value
""",
        encoding="utf-8",
    )

    values = parse_millproject(millproject_path)

    assert values["metric"] == "true"
    assert values["front"] == "board-F.Cu.gbr"
    assert "unknown" not in values


def test_format_millproject_writes_canonical_groups():
    content = format_millproject({"metric": "true", "zsafe": "5", "front": "front.gbr"})

    assert "# Generated by pcb2gcode-ui." in content
    assert "# Generic" in content
    assert "metric=true" in content
    assert "# Files" in content
    assert "front=front.gbr" in content
    assert "# CNC" in content
    assert "zsafe=5" in content
